CREATE OR REPLACE TABLE PB_DATA_CLASSIFICATION_MAPPING (
    SF_PRIVACY_CATEGORY STRING,
    SF_SEMANTIC_CATEGORY STRING,
    PB_DATA_CLASSIFICATION_NUM NUMBER,
    PB_DATA_CLASSIFICATION_LEVEL STRING,
    PB_DATA_CLASSIFICATION_TYPE STRING,  
    PB_DATA_CLASSIFICATION_CATEGORY STRING,
    SPECIAL_HANDLING_FLAG STRING,
    SPECIAL_HANDLING_REASON STRING,
    UNIQUE (SF_PRIVACY_CATEGORY, SF_SEMANTIC_CATEGORY)
);
